### ISSUE TITLE
What is Dockerfile.tmp?

### ISSUE THREAD

**Issue by pkubatrh** [sclorg/mariadb-container#162]
Mariadb 10.3 has a Dockerfile.tmp in the directory:
https://github.com/sclorg/mariadb-container/blob/master/10.3/Dockerfile.tmp

What is it used for?

**Comment by frenzymadness** [comment]
Probably a leftover from the copy-paste procedure when @hhorak created 10.5.

**Comment by hhorak** [comment]
Oh, yes, likely the result of `git mv ... ; cp -r ... ` calls. Sorry for that. We can remove this.
