### ISSUE TITLE
plugin-dir set incorrectly in my-base.cnf.template

### ISSUE THREAD

**Issue by jeredfloyd** [sclorg/mariadb-container#201]
Container scripts generate `/etc/my.cnf.d/base.cnf` from `/usr/share/container-scripts/mysql/pre-init/my-base.cnf.template`, which includes:

> `plugin-dir = ${MYSQL_PREFIX}/lib64/mysql/plugin`

However, plugins are installed by the package in `/usr/lib64/mariadb/plugin`, so plugins cannot be found by MariaDB.  I believe this should be changed to:
> `plugin-dir = ${MYSQL_PREFIX}/lib64/mariadb/plugin`

**Comment by FaramosCZ** [comment]
Fixed by https://github.com/sclorg/mariadb-container/pull/235
