### ISSUE TITLE
Broken container image build centos-mariadb-101-centos7-latest 

### ISSUE THREAD

**Issue by navidshaikh** [sclorg/mariadb-container#68]
Build `centos-mariadb-101-centos7-latest` is broken for CentOS base image.

Step failing in Dockerfile, [line 59](https://github.com/sclorg/mariadb-container/blob/master/10.1/Dockerfile#L59)
```
COPY 10.1/root-common /
```

and the following line 60 and 61 will also fail due to broken (relative path references).

[Full build logs] (https://registry.centos.org/pipeline-logs/MmU1ODM1NzA0M2/build_logs.txt)

**Comment by omron93** [comment]
@navidshaikh mariadb-container has to be built using

`cd 10.1; docker build -f Dockerfile ..` - the `..` context is required to make working instruction you mentioned

**Comment by phracek** [comment]
The steps how to build mariadb-container image on hosts like Fedora, CentOS7, RHEL are:
```
$ git clone https://github.com/sclorg/mariadb-container
$ cd mariadb-container
$ git submodule update --init
$ make build TARGET=<prefer_image> VERSIONS=10.3
```

In case of `centos7` it looks like:
```
$ git clone https://github.com/sclorg/mariadb-container
$ cd mariadb-container
$ git submodule update --init
$ make build TARGET=centos7 VERSIONS=10.3
```

Unfortunately building centos7 was disabled couple weeks ago.
In case you would like to build container for e.g. RHEL8 steps are similar.
```
$ git clone https://github.com/sclorg/mariadb-container
$ cd mariadb-container
$ git submodule update --init
$ make build TARGET=rhel8 VERSIONS=10.5
```

Closing this issue, as building, tagging and testing mariadb-container for versions 10.3 and 10.5 works properly. Feel free to re-open it.
