### ISSUE TITLE
Value of MYSQL_DEFAULTS_FILE seems to be ignored

### ISSUE THREAD

**Issue by valentinabojan** [sclorg/mariadb-container#94]
We are trying to create a persistence container running the following command:

`docker run --name persistence -e MYSQL_USER=user -e MYSQL_PASSWORD=pass -e MYSQL_DATABASE=db -e MYSQL_DEFAULTS_FILE=/persistence/conf/mariadb.cnf -v /home/persistence:/persistence/conf -p 3306:3306 centos/mariadb-102-centos7`

We expect to see that our mariadb configuration is loaded from /persistence/conf/mariadb.cnf file, but it is not. We only see the default configuration values in the database.

Are we missing something from the command above?

**Comment by omron93** [comment]
The command seems right. I've tried the same and it worked for me as expected.

@valentinabojan If you run the command with `-ti` option, what is the output? If you run `bash` inside the container are files in `/persistence/conf/` accessible as expected?

**Comment by valentinabojan** [comment]
@omron93 Indeed, the my.cnf file is loaded. My bad! I was always checking the value of 'wait_timeout' to see if has our custom value, but apparently this is a tricky one. All the other variables are correctly loaded. Thanks!
