### ISSUE TITLE
10.3 image not on DockerHub

### ISSUE THREAD

**Issue by hfuss** [sclorg/mariadb-container#98]
I'm getting a 404 when following the link in the 10.3 README. Looks like its not actually being uploaded to DockerHub? Is this intentional? We'd like to use the 10.3 image without having to build it and push it to our own registry.

**Comment by kubco2** [comment]
Hello, CentOS 8 is not released, it will be available on DockerHub after it will be released.

**Comment by hfuss** [comment]
Looks this got released a few months ago: https://hub.docker.com/r/centos/mariadb-103-centos7/tags
